package migration

import (
	"fmt"
	"os"

	"github.com/aerostackdev/cli/internal/devserver"
)

// ConvertWranglerToAerostack maps the configuration
func ConvertWranglerToAerostack(w *WranglerConfig) *devserver.AerostackConfig {
	cfg := &devserver.AerostackConfig{
		Name:              w.Name,
		Main:              w.Main,
		CompatibilityDate: w.CompatibilityDate,
		BuildCommand:      "npx esbuild src/index.ts --bundle --outfile=dist/worker.js",
		DevCommand:       "npx wrangler dev",
		DeployCommand:     "npx wrangler deploy",
	}

	if cfg.CompatibilityDate == "" {
		cfg.CompatibilityDate = "2024-01-01"
	}

	// Map D1 Databases
	for _, d := range w.D1Databases {
		cfg.D1Databases = append(cfg.D1Databases, devserver.D1Database{
			Binding:      d.Binding,
			DatabaseName: d.DatabaseName,
			DatabaseID:   d.DatabaseID,
		})
	}

	// Map KV Namespaces
	for _, kv := range w.KVNamespaces {
		cfg.KVNamespaces = append(cfg.KVNamespaces, devserver.KVNamespace{
			Binding: kv.Binding,
			ID:      kv.ID,
		})
	}

	return cfg
}

// GenerateAerostackToml writes the file
func GenerateAerostackToml(cfg *devserver.AerostackConfig, path string) error {
	var b string
	b += fmt.Sprintf("# Auto-generated by Aerostack Migration Tool\n")
	b += fmt.Sprintf("name = %q\n", cfg.Name)
	b += fmt.Sprintf("main = %q\n", cfg.Main)
	b += fmt.Sprintf("compatibility_date = %q\n\n", cfg.CompatibilityDate)
	b += fmt.Sprintf("[commands]\n")
	b += fmt.Sprintf("build = %q\n", cfg.BuildCommand)
	b += fmt.Sprintf("dev = %q\n", cfg.DevCommand)
	b += fmt.Sprintf("deploy = %q\n\n", cfg.DeployCommand)

	for _, db := range cfg.D1Databases {
		b += fmt.Sprintf("[[d1_databases]]\n")
		b += fmt.Sprintf("binding = %q\n", db.Binding)
		b += fmt.Sprintf("database_name = %q\n", db.DatabaseName)
		b += fmt.Sprintf("database_id = %q\n\n", db.DatabaseID)
	}

	if len(cfg.KVNamespaces) > 0 {
		b += fmt.Sprintf("# KV Namespaces (from wrangler.toml)\n")
		for _, kv := range cfg.KVNamespaces {
			b += fmt.Sprintf("[[kv_namespaces]]\n")
			b += fmt.Sprintf("binding = %q\n", kv.Binding)
			b += fmt.Sprintf("id = %q\n\n", kv.ID)
		}
	}

	return os.WriteFile(path, []byte(b), 0644)
}
