package mcpconvert

import (
	"fmt"
	"strings"
)

// ConvertResult holds the generated Worker code and wrangler.toml.
type ConvertResult struct {
	WorkerCode      string   // Generated Worker TypeScript/JavaScript
	WranglerToml    string   // Generated wrangler.toml
	DetectedSecrets []string // Env vars the Worker needs (for Aerostack gateway injection)
	Warnings        []string // Human-readable warnings
	ToolCount       int
}

// Transform takes an analysis result and generates a Cloudflare Worker wrapper.
func Transform(analysis *AnalysisResult) (*ConvertResult, error) {
	result := &ConvertResult{
		DetectedSecrets: analysis.EnvVars,
		ToolCount:       analysis.ToolCount,
	}

	// Collect warnings
	for _, w := range analysis.Warnings {
		prefix := "WARN"
		if w.Severity == "error" {
			prefix = "ERROR"
		}
		result.Warnings = append(result.Warnings, fmt.Sprintf("[%s] %s: %s", prefix, w.API, w.Message))
	}

	if analysis.HasHTTP && !analysis.HasStdio {
		result.Warnings = append(result.Warnings, "[INFO] This package already uses HTTP transport. Minimal conversion needed.")
	}

	// Generate Worker code
	result.WorkerCode = generateWorkerCode(analysis)

	// Generate wrangler.toml
	result.WranglerToml = generateWranglerToml(analysis)

	return result, nil
}

// generateWorkerCode produces a Cloudflare Worker that wraps the original MCP server.
func generateWorkerCode(a *AnalysisResult) string {
	slug := SanitizeSlug(a.PackageName)

	// Build secret extraction lines
	var secretLines []string
	for _, env := range a.EnvVars {
		headerKey := envToHeaderKey(env)
		secretLines = append(secretLines,
			fmt.Sprintf(`    %s: request.headers.get('%s') ?? env.%s ?? '',`, env, headerKey, env),
		)
	}
	secretBlock := strings.Join(secretLines, "\n")

	// Build process.env override
	var envOverrides []string
	for _, env := range a.EnvVars {
		envOverrides = append(envOverrides, fmt.Sprintf(`    process.env.%s = secrets.%s;`, env, env))
	}
	envOverrideBlock := strings.Join(envOverrides, "\n")

	code := fmt.Sprintf(`/**
 * Aerostack MCP Worker — auto-converted from %s
 *
 * This Worker wraps the original stdio-based MCP server to work over HTTP.
 * Secrets are injected via Aerostack gateway headers (X-Mcp-Secret-*).
 *
 * Generated by: aerostack mcp convert
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

// ──── Import original server setup ────
// The original package's tool definitions are imported and re-registered.
// If this file doesn't compile, manually copy tool definitions from the source.
// Entry point: %s

// ──── Secret extraction from Aerostack gateway headers ────
function extractSecrets(request: Request, env: Record<string, string>): Record<string, string> {
  return {
%s
  };
}

// ──── MCP over HTTP handler ────
//
// Pattern: The gateway sends JSON-RPC 2.0 POST requests.
// We handle initialize, tools/list, and tools/call.
//
// For most npm MCP packages, you can import their server instance
// and let it handle tool registration. This wrapper just bridges
// the transport layer.

interface Env {
%s
}

// Re-export the original server with HTTP transport.
// If the original package exports a configured McpServer, import it here.
// Otherwise, copy the tool definitions from the source entry point.

const server = new McpServer({
  name: "%s",
  version: "1.0.0",
});

// ╔══════════════════════════════════════════════════════════════╗
// ║  PASTE TOOL DEFINITIONS HERE                                ║
// ║                                                             ║
// ║  Copy server.tool(...) calls from: %s    ║
// ║                                                             ║
// ║  Example:                                                   ║
// ║  server.tool("my_tool", "desc", { arg: z.string() },       ║
// ║    async ({ arg }) => {                                     ║
// ║      const token = process.env.MY_TOKEN;                    ║
// ║      return { content: [{ type: "text", text: "ok" }] };   ║
// ║    }                                                        ║
// ║  );                                                         ║
// ╚══════════════════════════════════════════════════════════════╝

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Only accept POST
    if (request.method !== "POST") {
      return new Response(JSON.stringify({ jsonrpc: "2.0", error: { code: -32600, message: "POST required" } }), {
        status: 405,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Extract secrets from gateway headers
    const secrets = extractSecrets(request, env as any);

    // Inject into process.env so original tool code works unchanged
    if (typeof globalThis.process === "undefined") {
      (globalThis as any).process = { env: {} };
    }
%s

    try {
      const body = await request.json() as any;
      const { method, params, id } = body;

      // tools/list
      if (method === "tools/list") {
        const tools = (server as any)._registeredTools;
        const toolList = tools
          ? Object.entries(tools).map(([name, t]: [string, any]) => ({
              name,
              description: t.description ?? "",
              inputSchema: t.inputSchema ?? { type: "object", properties: {} },
            }))
          : [];
        return jsonResponse({ jsonrpc: "2.0", id, result: { tools: toolList } });
      }

      // tools/call
      if (method === "tools/call") {
        const toolName = params?.name;
        const args = params?.arguments ?? {};
        const tools = (server as any)._registeredTools;
        const tool = tools?.[toolName];
        if (!tool) {
          return jsonResponse({
            jsonrpc: "2.0", id,
            error: { code: -32602, message: "Unknown tool: " + toolName },
          });
        }

        try {
          const result = await tool.callback(args, { server });
          return jsonResponse({ jsonrpc: "2.0", id, result });
        } catch (err: any) {
          return jsonResponse({
            jsonrpc: "2.0", id,
            result: {
              content: [{ type: "text", text: "Error: " + (err?.message ?? String(err)) }],
              isError: true,
            },
          });
        }
      }

      // initialize
      if (method === "initialize") {
        return jsonResponse({
          jsonrpc: "2.0", id,
          result: {
            protocolVersion: "2024-11-05",
            capabilities: { tools: { listChanged: false } },
            serverInfo: { name: "%s", version: "1.0.0" },
          },
        });
      }

      return jsonResponse({
        jsonrpc: "2.0", id,
        error: { code: -32601, message: "Method not supported: " + method },
      });
    } catch (err: any) {
      return jsonResponse({
        jsonrpc: "2.0", id: null,
        error: { code: -32700, message: "Parse error: " + (err?.message ?? String(err)) },
      }, 400);
    }
  },
};

function jsonResponse(body: any, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
`, a.PackageName, a.EntryPoint, secretBlock,
		generateEnvInterface(a.EnvVars),
		slug, padRight(a.EntryPoint, 20),
		envOverrideBlock,
		slug,
	)

	return code
}

// generateWranglerToml produces a wrangler.toml for the converted Worker.
func generateWranglerToml(a *AnalysisResult) string {
	slug := SanitizeSlug(a.PackageName)

	toml := fmt.Sprintf(`# Auto-generated by: aerostack mcp convert
# Source: %s

name = "%s"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Uncomment if deploying to your own Cloudflare account:
# [vars]
`, a.PackageName, slug)

	// Add env var placeholders
	for _, env := range a.EnvVars {
		toml += fmt.Sprintf("# %s = \"your-%s-here\"\n", env, strings.ToLower(strings.ReplaceAll(env, "_", "-")))
	}

	return toml
}

// generateEnvInterface creates TypeScript env interface declarations.
func generateEnvInterface(envVars []string) string {
	var lines []string
	for _, env := range envVars {
		lines = append(lines, fmt.Sprintf("  %s?: string;", env))
	}
	if len(lines) == 0 {
		return "  [key: string]: string;"
	}
	return strings.Join(lines, "\n")
}

// SanitizeSlug converts a package name to a valid Worker name (exported for commands).
func SanitizeSlug(name string) string {
	// @org/package-name -> package-name
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		name = name[idx+1:]
	}
	// Replace non-alphanumeric with hyphens
	slug := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		if r >= 'A' && r <= 'Z' {
			return r + 32 // toLower
		}
		return '-'
	}, name)
	return strings.Trim(slug, "-")
}

// envToHeaderKey converts GITHUB_TOKEN to X-Mcp-Secret-GITHUB-TOKEN.
func envToHeaderKey(env string) string {
	return "X-Mcp-Secret-" + strings.ReplaceAll(env, "_", "-")
}

func padRight(s string, n int) string {
	if len(s) >= n {
		return s
	}
	return s + strings.Repeat(" ", n-len(s))
}
